#!/bin/bash

batterycheck(){
	if [ $(battery) -gt 70 ]
	then
		echo ""
	elif [ $(battery) -gt 50 ]
	then
		echo ""
	elif [ $(battery) -gt 40 ]
	then
		echo ""
	elif [ $(battery) -gt 1 ]
	then
		echo ""
	else
		echo ""
	fi
}

volumecheck(){
	if [ $(pamixer --get-volume) -gt 50 ]
	then
		echo ""
	elif [ $(pamixer --get-volume) -gt 10 ]
	then
		echo ""
	else
		echo "" 
	fi
}

while true; do
	xsetroot -name "|  $(date +%H:%M) |  $(date +%d/%m/%y) | $(batterycheck) $(battery) | $(volumecheck) $(pamixer --get-volume) |"
	sleep 1s
done
